/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "index.html",
    "./src/**/*.{vue,ts}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Poppins", "Roboto", "sans-serif"],
      },
      colors: {
        "primary": "var(--md-sys-color-primary)",
        "on-primary": "var(--md-sys-color-on-primary)",
        "primary-container": "var(--md-sys-color-primary-container)",
        "on-primary-container": "var(--md-sys-color-on-primary-container)",
        "secondary": "var(--md-sys-color-secondary)",
        "on-secondary": "var(--md-sys-color-on-secondary)",
        "secondary-container": "var(--md-sys-color-secondary-container)",
        "on-secondary-container": "var(--md-sys-color-on-secondary-container)",
        "tertiary": "var(--md-sys-color-tertiary)",
        "on-tertiary": "var(--md-sys-color-on-tertiary)",
        "tertiary-container": "var(--md-sys-color-tertiary-container)",
        "on-tertiary-container": "var(--md-sys-color-on-tertiary-container)",
        "error": "var(--md-sys-color-error)",
        "on-error": "var(--md-sys-color-on-error)",
        "error-container": "var(--md-sys-color-error-container)",
        "on-error-container": "var(--md-sys-color-on-error-container)",
        "background": "var(--md-sys-color-background)",
        "on-background": "var(--md-sys-color-on-background)",
        "surface": "var(--md-sys-color-surface)",
        "on-surface": "var(--md-sys-color-on-surface)",
        "surface-variant": "var(--md-sys-color-surface-variant)",
        "on-surface-variant": "var(--md-sys-color-on-surface-variant)", 
        "outline": "var(--md-sys-color-outline)",
        "outline-variant": "var(--md-sys-color-outline-variant)",
        "shadow": "var(--md-sys-color-shadow)",
        "scrim": "var(--md-sys-color-scrim)",
        "inverse-surface": "var(--md-sys-color-inverse-surface)",
        "inverse-on-surface": "var(--md-sys-color-inverse-on-surface)",
        "inverse-primary": "var(--md-sys-color-inverse-primary)",
        "primary-25": "var(--md-sys-color-primary-25)",
        "primary-50": "var(--md-sys-color-primary-50)",
        "primary-75": "var(--md-sys-color-primary-75)",
        "on-primary-25": "var(--md-sys-color-on-primary-25)",
        "on-primary-50": "var(--md-sys-color-on-primary-50)",
        "on-primary-75": "var(--md-sys-color-on-primary-75)",
        "primary-container-25": "var(--md-sys-color-primary-container-25)",
        "primary-container-50": "var(--md-sys-color-primary-container-50)",
        "primary-container-75": "var(--md-sys-color-primary-container-75)",
        "on-primary-container-25": "var(--md-sys-color-on-primary-container-25)",
        "on-primary-container-50": "var(--md-sys-color-on-primary-container-50)",
        "on-primary-container-75": "var(--md-sys-color-on-primary-container-75)",
        "secondary-25": "var(--md-sys-color-secondary-25)",
        "secondary-50": "var(--md-sys-color-secondary-50)",
        "secondary-75": "var(--md-sys-color-secondary-75)",
        "on-secondary-25": "var(--md-sys-color-on-secondary-25)",
        "on-secondary-50": "var(--md-sys-color-on-secondary-50)",
        "on-secondary-75": "var(--md-sys-color-on-secondary-75)",
        "secondary-container-25": "var(--md-sys-color-secondary-container-25)",
        "secondary-container-50": "var(--md-sys-color-secondary-container-50)",
        "secondary-container-75": "var(--md-sys-color-secondary-container-75)",
        "on-secondary-container-25": "var(--md-sys-color-on-secondary-container-25)",
        "on-secondary-container-50": "var(--md-sys-color-on-secondary-container-50)",
        "on-secondary-container-75": "var(--md-sys-color-on-secondary-container-75)",
        "tertiary-25": "var(--md-sys-color-tertiary-25)",
        "tertiary-50": "var(--md-sys-color-tertiary-50)",
        "tertiary-75": "var(--md-sys-color-tertiary-75)",
        "on-tertiary-25": "var(--md-sys-color-on-tertiary-25)",
        "on-tertiary-50": "var(--md-sys-color-on-tertiary-50)",
        "on-tertiary-75": "var(--md-sys-color-on-tertiary-75)",
        "tertiary-container-25": "var(--md-sys-color-tertiary-container-25)",
        "tertiary-container-50": "var(--md-sys-color-tertiary-container-50)",
        "tertiary-container-75": "var(--md-sys-color-tertiary-container-75)",
        "on-tertiary-container-25": "var(--md-sys-color-on-tertiary-container-25)",
        "on-tertiary-container-50": "var(--md-sys-color-on-tertiary-container-50)",
        "on-tertiary-container-75": "var(--md-sys-color-on-tertiary-container-75)",
        "error-25": "var(--md-sys-color-error-25)",
        "error-50": "var(--md-sys-color-error-50)",
        "error-75": "var(--md-sys-color-error-75)",
        "on-error-25": "var(--md-sys-color-on-error-25)",
        "on-error-50": "var(--md-sys-color-on-error-50)",
        "on-error-75": "var(--md-sys-color-on-error-75)",
        "error-container-25": "var(--md-sys-color-error-container-25)",
        "error-container-50": "var(--md-sys-color-error-container-50)",
        "error-container-75": "var(--md-sys-color-error-container-75)",
        "on-error-container-25": "var(--md-sys-color-on-error-container-25)",
        "on-error-container-50": "var(--md-sys-color-on-error-container-50)",
        "on-error-container-75": "var(--md-sys-color-on-error-container-75)",
        "background-25": "var(--md-sys-color-background-25)",
        "background-50": "var(--md-sys-color-background-50)",
        "background-75": "var(--md-sys-color-background-75)",
        "on-background-25": "var(--md-sys-color-on-background-25)",
        "on-background-50": "var(--md-sys-color-on-background-50)",
        "on-background-75": "var(--md-sys-color-on-background-75)",
        "surface-25": "var(--md-sys-color-surface-25)",
        "surface-50": "var(--md-sys-color-surface-50)",
        "surface-75": "var(--md-sys-color-surface-75)",
        "on-surface-25": "var(--md-sys-color-on-surface-25)", 
        "on-surface-50": "var(--md-sys-color-on-surface-50)",
        "on-surface-75": "var(--md-sys-color-on-surface-75)",
        "surface-variant-25": "var(--md-sys-color-surface-variant-25)",
        "surface-variant-50": "var(--md-sys-color-surface-variant-50)",
        "surface-variant-75": "var(--md-sys-color-surface-variant-75)",
        "on-surface-variant-25": "var(--md-sys-color-on-surface-variant-25)",
        "on-surface-variant-50": "var(--md-sys-color-on-surface-variant-50)",
        "on-surface-variant-75": "var(--md-sys-color-on-surface-variant-75)",
      }
    },
  } 
}

